// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBluZQEJ_3feVQ-YMpD0f7ODDCNOQQf9FY',
    appId: '1:951152271658:web:3d9b644d6cfba165227e53',
    messagingSenderId: '951152271658',
    projectId: 'whatsapp-backend-fa178',
    authDomain: 'whatsapp-backend-fa178.firebaseapp.com',
    storageBucket: 'whatsapp-backend-fa178.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-KTBA977oNBwvNgO6FRQ0hPgukz48MlY',
    appId: '1:951152271658:android:db9f55928e694ceb227e53',
    messagingSenderId: '951152271658',
    projectId: 'whatsapp-backend-fa178',
    storageBucket: 'whatsapp-backend-fa178.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFvdveArPfoS17rPUHb8k-6cqZvSP5h4Q',
    appId: '1:951152271658:ios:53031c72d0ff301f227e53',
    messagingSenderId: '951152271658',
    projectId: 'whatsapp-backend-fa178',
    storageBucket: 'whatsapp-backend-fa178.appspot.com',
    iosClientId: '951152271658-jj0ng829n2ddul1oi58s6sg7jqvnpiqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoWhatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFvdveArPfoS17rPUHb8k-6cqZvSP5h4Q',
    appId: '1:951152271658:ios:53031c72d0ff301f227e53',
    messagingSenderId: '951152271658',
    projectId: 'whatsapp-backend-fa178',
    storageBucket: 'whatsapp-backend-fa178.appspot.com',
    iosClientId: '951152271658-jj0ng829n2ddul1oi58s6sg7jqvnpiqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoWhatsapp',
  );
}
